#!/usr/local/bin/python3

import openai
import sys

openai.api_key = 'your-key-here'

def prompt(chat):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        max_tokens=250,
        temperature=0.1,
        messages=chat
    )

    return response['choices'][0]['message']['content'].strip("[]` ")

if __name__ == "__main__":
    # Do we have stdin
    if not sys.stdin.isatty():
        if len(sys.argv) == 1:
            print("no modifier given")
            exit(-1)

        modifier = ' '.join(sys.argv[1:])
        stdin = sys.stdin.read()
        response = prompt(
            [
                {"role": "system", "content": "You are an assistant that is an expert at modifying text"},
                {"role": "user", "content": "I'm going to give you text to work on and instructions how to modify it"},
                {"role": "assistant", "content": "ok"},
                {"role": "user", "content": "Only respond with the modified text and NOT anything else."},
                {"role": "assistant", "content": "ok"},
                {"role": "user", "content": f"Here is the text: '{stdin}'"},
                {"role": "assistant", "content": "ok"},
                {"role": "user", "content": f"Here is how to modify the text: {modifier}"}
            ]
        )
        print(response)
    else:
        if len(sys.argv) == 1:
            print("no prompt given")
            exit(-1)

        text = ' '.join(sys.argv[1:])
        response = prompt(
            [
                {"role": "system", "content": "You are an assistant that is an expert at generating text"},
                {"role": "user", "content": "I'm going to give you instructions on what text to generate."},
                {"role": "assistant", "content": "ok"},
                {"role": "user", "content": "Only interpret my instructions as a means to generate text."},
                {"role": "assistant", "content": "ok"},
                {"role": "user", "content": f"instructions: {text}"}
            ]
        )
        print(response)
