#!/usr/local/bin/python3

import openai
import os
import subprocess
import sys

openai.api_key = 'your key here'

def prompt(chat):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        max_tokens=250,
        temperature=0.1,
        messages=chat
    )

    return response['choices'][0]['message']['content'].strip("[]` ")

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("No command text given")
        exit()

    user_input = ' '.join(sys.argv[1:])
    command = prompt(
            [
                {"role": "system", "content": "You are an assistant that is an expert using the terminal"},
                {"role": "user", "content": "I will give you a text description of a command I want to run"},
                {"role": "assistant", "content": "ok"},
                {"role": "user", "content": "Do NOT respond with any English text, only terminal commands."},
                {"role": "assistant", "content": "ok"},
                {"role": "user", "content": f"How do you ${user_input}?"}
            ]
    )
    
    print(f"command: {command}")
    
    proceed = input("run? (yes/no): ")
    if proceed.lower() == "yes" or proceed.lower() == "y" or len(proceed) == 0:
        shell_pid = os.getpid()
        subprocess.Popen(command, shell=True, executable='/bin/bash', env={'PARENT_PID': str(shell_pid)})
    else:
        print("cancelled")

